### ISSUE TITLE
Erreur 500 à l'inscritption

### ISSUE THREAD

**Issue by hemorragy** [assemblee-virtuelle/grands-voivins-v3#1]
En essayant de me créer un compte via deux liens différents : http://reseau.lesgrandsvoisins.org/register/Ef_0KfsHTUv7ATrC5vK3lVBladhgYOUaGXN2cRF9NzQ
http://reseau.lesgrandsvoisins.org/register/a-NaNjkuj5ljYrDkvGeIFo3FaFUGRzfEQCON6DI68sA

Je me suis retrouvé après avoir rentré mes informations et appuyé sur enregistrer sur une page erreur 500, avec mon compte pas créé. J'ai essayé de changer d’adresse mail, de login et de mot de passe.

**Comment by SebLemoine** [comment]
Problème résolu avec une mise à jour de la base de donnée !
